spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useUnicode=true&useSSL=false
#    url: jdbc:oracle:thin:@133.160.94.44:1521:premdb
    username: root
    password: 1234
    druid:
      initial-size: 3
      max-active: 6
      min-evictable-idle-time-millis: 100000
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: oracle
          config:
            delete-allow: false
            drop-table-allow: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       format_sql: true

  http:
    encoding:
      charset: UTF-8
      force-response: true
      force-request: true
      enabled: true
server:
  port: 8090
